def FindMotifDna(N, K):
    positions = []
    for i in range(len(N) - len(K) + 1):
        subStr = N[i: i + len(K)]
        if subStr == K:
            positions.append(i + 1)
    return positions
N = "AACTTCGATAAGGATCTTCGATCAACTTCGATCGCTTGCTTCGATCTACTTCGATATACTTCGATCTTCGATTGGCTTCGATCGCGCCTTCGATGACTTCGATCTTCGATCGCCTTCGATAGAGGCTTCGATCTTCGATCTTCGATATATCTATCTTCGATACTCTCTTCGATCCTTCGATCTTCGATCTTCGATTCTTCGATACCTACGCTTCGATTCTTCGATCAGTCTTCGATTGCGGGACTCTTCGATTAGCGTAACACCCACTTCGATCGGGCTTCGATACCGTGCTTCGATATAGCCTTCGATTTGAACGCGACTTCGATGCGCTTCGATGACTTCGATCTTCGATTCTTCGATCTTCGATGACTTCGATAACTAGACTTCGATACGCACCTTCGATCCTTCGATGACTTCGATACTTCGATCTTCGATACCTTCGATCTAACTTCGATTGTGCTTCGATGCTTCTTCGATCGCTTCGATCTGCTTCGATCCACTTCGATTCCCCGCTTCGATCTTCGATAGTCCTTCGATCTTCGATATCTTCGATGTCTTCGATCTTCGATCGCGCTTCGATCTTCGATAGCTTCGATGCTTCGATACATGCTTCGATGATAATCAATTGATACTTCGATCACTTCGATCTTCGATGACTTCGATTCTTCGATCTCTAGCTTCGATCTTCGATGAGCTTCGATCACTTCGATGACTTCGATTGCCCTTCGATGCTTCGATCTTCGATTACTTCGATCTTCGATATCATACGGCTTCGATGCCTACTTCGATCTTCGATTCTTCGATGCATCAGTAATCTTCGATCGCTTCGATCTCTCTTCGATTTCCTTCGATCTTCGATCCCTTCGATCCTTCGATGCGCTTCGATGCTACTTCGATTCCTTCGATGCTTCGATACTTCGATTCGCTTCGATGCTTCGATACTTCGATTCCCGCTTCGATTCTTCGATTACTTCGATCTTCGAT"
K = "CTTCGATCT"
positions = FindMotifDna(N, K)
print(" ".join(map(str, positions)))